import Head from "next/head";
import Message from "../components/message";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  // State of all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));

    // Upadate posts in real time
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Productive Minds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-10 text-lg font-medium px-10">
        <h2 className="py-5 pb-10">What other people are saying</h2>
        {allPosts.map((post) => (
          <div className="mb-5">
            <Message key={post.id} {...post}>
              <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
                <button>
                  {post.comments?.length > 0 ? post.comments?.length : 0}{" "}
                  comments
                </button>
              </Link>
            </Message>
          </div>
        ))}
      </div>
    </div>
  );
}
